# -*- coding: utf-8 -*-
"""sales expencive analysics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sa8xTlJ4XW98XRDl0DxzrjhRUA1vFYVR
"""

import pandas as pd
import numpy as np

import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/train.csv")

Date = df["Row ID"].to_numpy()
print(Date)

Date = df["Order ID"].to_numpy()
print(Date)

Date = df["Order Date"].to_numpy()
print(Date)

Date = df["Ship Date"].to_numpy()
print(Date)

Date = df["Ship Mode"].to_numpy()
print(Date)

Date = df["Customer ID"].to_numpy()
print(Date)

Date = df["Customer Name"].to_numpy()
print(Date)

Date = df["Segment"].to_numpy()
print(Date)

Date = df["Country"].to_numpy()
print(Date)

Date = df["City"].to_numpy()
print(Date)

Date = df["State"].to_numpy()
print(Date)

Date = df["Postal Code"].to_numpy()
print(Date)

Date = df["Region"].to_numpy()
print(Date)

Date = df["Product ID"].to_numpy()
print(Date)

Date = df["Category"].to_numpy()
print(Date)

Date = df["Sub-Category"].to_numpy()
print(Date)

Date = df["Product Name"].to_numpy()
print(Date)

Date = df["Sales"].to_numpy()
print(Date)

print("Missing values in each column:")
display(df.isnull().sum())

# Sales by Store
store_sales = df.groupby('Customer Name')['Sales'].sum().reset_index().sort_values(by='Sales', ascending=False)

print("Top 10 Stores by Sales:")
display(store_sales.head(10))

print("\nBottom 10 Stores by Sales:")
display(store_sales.tail(10))

# Best-selling Products
product_sales = df.groupby('Product Name')['Sales'].sum().reset_index().sort_values(by='Sales', ascending=False)

print("Top 10 Best-Selling Products:")
display(product_sales.head(10))

# Low-performing Products
print("Bottom 10 Low-Performing Products:")
display(product_sales.tail(10))

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 7))
sns.barplot(x='Customer Name', y='Sales', data=store_sales.head(10))
plt.title('Top 10 Customers by Sales')
plt.xlabel('Customer Name')
plt.ylabel('Total Sales')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

plt.figure(figsize=(15, 7))
sns.barplot(x='Customer Name', y='Sales', data=store_sales.tail(10))
plt.title('Bottom 10 Customers by Sales')
plt.xlabel('Customer Name')
plt.ylabel('Total Sales')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 7))
sns.barplot(x='Product Name', y='Sales', data=product_sales.head(10))
plt.title('Top 10 Best-Selling Products')
plt.xlabel('Product Name')
plt.ylabel('Total Sales')
plt.xticks(rotation=90, ha='right')
plt.tight_layout()
plt.show()

plt.figure(figsize=(15, 7))
sns.barplot(x='Product Name', y='Sales', data=product_sales.tail(10))
plt.title('Bottom 10 Low-Performing Products')
plt.xlabel('Product Name')
plt.ylabel('Total Sales')
plt.xticks(rotation=90, ha='right')
plt.tight_layout()
plt.show()

# Convert 'Order Date' and 'Ship Date' columns to datetime objects
# Assuming the format is DD/MM/YYYY based on previous output
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d/%m/%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%d/%m/%Y')

print("Date columns converted successfully. Verifying data types:")
display(df[['Order Date', 'Ship Date']].dtypes)

initial_rows = df.shape[0]
df.drop_duplicates(inplace=True)
final_rows = df.shape[0]

print(f"Initial number of rows: {initial_rows}")
print(f"Number of rows after removing duplicates: {final_rows}")
print(f"Number of duplicate rows removed: {initial_rows - final_rows}")

total_sales = df['Sales'].sum()
print(f"Total Sales: ${total_sales:,.2f}")

average_sales = df['Sales'].mean()
print(f"Average Sales: ${average_sales:,.2f}")

max_sales = df['Sales'].max()
print(f"Maximum Sales: ${max_sales:,.2f}")

min_sales = df['Sales'].min()
print(f"Minimum Sales: ${min_sales:,.2f}")

# Extract year for yearly trend analysis
df['Order Year'] = df['Order Date'].dt.year

yearly_sales = df.groupby('Order Year')['Sales'].sum().reset_index()

plt.figure(figsize=(10, 6))
sns.barplot(x='Order Year', y='Sales', data=yearly_sales)
plt.title('Yearly Sales Trend')
plt.xlabel('Year')
plt.ylabel('Total Sales')
plt.grid(axis='y')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Sales by Ship Mode
ship_mode_sales = df.groupby('Ship Mode')['Sales'].sum().reset_index().sort_values(by='Sales', ascending=False)
plt.figure(figsize=(10, 6))
sns.barplot(x='Ship Mode', y='Sales', data=ship_mode_sales)
plt.title('Sales by Ship Mode')
plt.xlabel('Ship Mode')
plt.ylabel('Total Sales')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.boxplot(y=df['Sales'])
plt.title('Box Plot of Sales for Outlier Detection')
plt.ylabel('Sales Amount')
plt.grid(axis='y', alpha=0.75)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Select numerical columns for correlation analysis
numerical_cols = df.select_dtypes(include=['number']).columns

# Drop 'Row ID' and 'Postal Code' if they exist and are not relevant for correlation analysis
numerical_cols = numerical_cols.drop(['Row ID', 'Postal Code'], errors='ignore')

# Calculate the correlation matrix
correlation_matrix = df[numerical_cols].corr()

plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix of Numerical Features')
plt.show()

# Sales by Segment
segment_sales = df.groupby('Segment')['Sales'].sum().reset_index().sort_values(by='Sales', ascending=False)
plt.figure(figsize=(10, 6))
sns.barplot(x='Segment', y='Sales', data=segment_sales)
plt.title('Sales by Segment')
plt.xlabel('Segment')
plt.ylabel('Total Sales')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Sales by Category
category_sales = df.groupby('Category')['Sales'].sum().reset_index().sort_values(by='Sales', ascending=False)
plt.figure(figsize=(10, 6))
sns.barplot(x='Category', y='Sales', data=category_sales)
plt.title('Sales by Product Category')
plt.xlabel('Product Category')
plt.ylabel('Total Sales')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Sales by Region
region_sales = df.groupby('Region')['Sales'].sum().reset_index().sort_values(by='Sales', ascending=False)
plt.figure(figsize=(10, 6))
sns.barplot(x='Region', y='Sales', data=region_sales)
plt.title('Sales by Region')
plt.xlabel('Region')
plt.ylabel('Total Sales')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Group sales by Order Date
daily_sales = df.groupby('Order Date')['Sales'].sum().reset_index()

plt.figure(figsize=(14, 7))
sns.lineplot(x='Order Date', y='Sales', data=daily_sales)
plt.title('Total Sales Over Time')
plt.xlabel('Order Date')
plt.ylabel('Total Sales')
plt.grid(True)
plt.show()

# Extract month and year for monthly trend analysis
df['Order YearMonth'] = df['Order Date'].dt.to_period('M')

monthly_sales = df.groupby('Order YearMonth')['Sales'].sum().reset_index()
monthly_sales['Order YearMonth'] = monthly_sales['Order YearMonth'].astype(str)

plt.figure(figsize=(14, 7))
sns.lineplot(x='Order YearMonth', y='Sales', data=monthly_sales, sort=False)
plt.title('Monthly Sales Trend')
plt.xlabel('Month-Year')
plt.ylabel('Total Sales')
plt.xticks(rotation=90)
plt.grid(True)
plt.show()

# Extract day of the week for weekly trend analysis
df['DayOfWeek'] = df['Order Date'].dt.day_name()

dayofweek_sales = df.groupby('DayOfWeek')['Sales'].sum().reindex([
    'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'
]).reset_index()

plt.figure(figsize=(10, 6))
sns.barplot(x='DayOfWeek', y='Sales', data=dayofweek_sales)
plt.title('Sales by Day of the Week')
plt.xlabel('Day of Week')
plt.ylabel('Total Sales')
plt.grid(axis='y')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(df['Sales'], bins=50, kde=True)
plt.title('Distribution of Sales')
plt.xlabel('Sales Amount')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)
plt.show()

print("Sales distribution details:")
display(df['Sales'].describe())

print("Unique values in 'Ship Mode':", df['Ship Mode'].unique())
print("Unique values in 'Segment':", df['Segment'].unique())
print("Unique values in 'Category':", df['Category'].unique())
print("Unique values in 'Region':", df['Region'].unique())